### ISSUE TITLE
Extra spaces added even when lines include trailing space

### ISSUE THREAD

**Issue by dmolesUC3** [abrookins/WrapToColumn#10]
Given the following (where `⋅` indicates a space):

```
The⋅quick⋅brown⋅fox⋅
jumps⋅over⋅the⋅lazy⋅
dog
```

I'd expect:

```
The⋅quick⋅brown⋅fox⋅jumps⋅over⋅the⋅lazy⋅dog
```

But I get:

```
The⋅quick⋅brown⋅fox⋅⋅jumps⋅over⋅the⋅lazy⋅⋅dog
```

Ideally, one might even collapse extra end-of-line space, so that:

```
The⋅quick⋅brown⋅fox⋅⋅⋅⋅⋅⋅⋅
jumps⋅over⋅the⋅lazy⋅⋅⋅⋅⋅⋅
dog
           ↓

The⋅quick⋅brown⋅fox⋅jumps⋅over⋅the⋅lazy⋅dog
```

instead of

```
The⋅quick⋅brown⋅fox⋅⋅⋅⋅⋅⋅⋅⋅jumps⋅over⋅the⋅lazy⋅⋅⋅⋅⋅⋅⋅dog
```

but I'd settle for not adding extra.

**Comment by abrookins** [comment]
Yuck, that's terrible. Thank you for reporting. I'm planning a push to work
on this plugin soon, and I'll check this out then.

**Comment by dmolesUC3** [comment]
Thanks!
