### ISSUE TITLE
Unable to run version 1.3 with IntelliJ 14.1.6 on Mac

### ISSUE THREAD

**Issue by ngriffin7a** [abrookins/WrapToColumn#17]
When I invoke the keyboard shortcut, I see the following error in the IntelliJ console:
7:32:58 PM NoClassDefFoundError: kotlin/jvm/internal/Intrinsics

Perhaps version 1.3 only compatible with IntelliJ 15? Thanks.

**Comment by yaronyg** [comment]
+1

Wrap to Column has been a life saver for my project. I have to write a lot of jsdoc and we have an 80 character limit. To make matters worse we have older code which was created before the 80 character limit. If it weren't for WrapToColumn I would have lost my mind dealing with this. I really appreciate the plugin. I hope it gets fixed soon.

**Comment by abrookins** [comment]
Looks like I blew it when I switched to Kotlin. I'll work on this tonight!

**Comment by yaronyg** [comment]
Yes! Thank you!!!

**Comment by abrookins** [comment]
@yaronyg Did that fix it for you? I tested 1.3.1 locally with Intellij Ultimate 14.1.6 and it resolved the issue.

**Comment by ngriffin7a** [comment]
@abrookins I just tried 1.3.1 with IntelliJ 14.1.6 and it works! Thanks so much for the fast fix! :-)

**Comment by yaronyg** [comment]
@abrookins Yup, that's why I said thank you. I only said it once I tested it. :)
