### ISSUE TITLE
Can wrap be more 'fill-paragraph' like

### ISSUE THREAD

**Issue by ebergerson** [abrookins/WrapToColumn#21]
I use WrapToColumn in both IDEA and PyCharm.  It is incredibly helpful so thank you.  And thank you in advance for the work you are planning to do on MarkDown, as I use it primarily on MarkDown text.

Currently, I need to highlight all of the lines I want to wrap.
I was wondering if you would consider making it operate more like 'fill-paragraph' or adding an additional wrapping method called "Fill Paragraph" that would wrap all of the lines in the paragraph containing the current cursor.

Thanks.

**Comment by abrookins** [comment]
Sure! That sounds like a great addition. I'll see if I can get it in this month.

**Comment by abrookins** [comment]
Check out the latest version, 1.4.0, for a new action -- Wrap Paragraph to Column. Let me know how it works, @ebergerson.
