### ISSUE TITLE
support for actually binding to `gq`?

### ISSUE THREAD

**Issue by fantapop** [abrookins/WrapToColumn#25]
Once i bind reformat to gq, all of my other vim commands that start with g stop working.  Is there a work around for this?

**Comment by abrookins** [comment]
Hmm. I just tested this in Intellij Ultimate 2017.3 with IdeaVim 0.49 and couldn't reproduce. Here's what I did:

```
map gq :action com.andrewbrookins.idea.wrap.WrapParagraphAction<CR>
map gr :action VimWindowRight<CR>
```

That is, I tested two commands that start with `g`. Both seem to work. Can you include steps to reproduce? Thanks!

**Comment by abrookins** [comment]
This seems to be working. Reopen if not!
