### ISSUE TITLE
Can "Wrap Line to Column" end with no selection if it began with no selection?

### ISSUE THREAD

**Issue by maverickwoo** [abrookins/WrapToColumn#26]
The current behavior is it will leave the wrapped text of the original line selected, ripe for accidental overwriting on subsequent typing. This behavior also seems counterintuitive given the command's name because the name does not suggest the resulting text will always be selected.

For your consideration. Thank you!

**Comment by abrookins** [comment]
Thanks for the report. I agree with you! Been struggling to find the time to work on WrapToColumn lately, but I'll do my best!

**Comment by abrookins** [comment]
Should be fixed in 1.7.0, now published to the Plugins Marketplace.
