### ISSUE TITLE
Use single HTML tag as paragraph break for javadoc

### ISSUE THREAD

**Issue by viliam-durina** [abrookins/WrapToColumn#27]
We use this style of javadoc comments:
```
/**
 * Paragraph1.
 * <p>
 * Paragraph2.
 */
```

Reformatting this gives us:
```
/**
 * Paragraph1. <p> Paragraph2.
 */
```
It would be nice if sole `<p>` (or more generally sole HTML tag or tags) will be treated as paragraph break. This style is also used in JDK (see `java.lang.String`, for example).

**Comment by omega** [comment]
perhaps semi-related, it would be nice if "Wrap paragraph" worked better for HTML, only wrapping the current element you're in, not needing blank lines above and below

**Comment by abrookins** [comment]
Fixed now!
