### ISSUE TITLE
Selecting a partial line without the indent results in inconsistent final indentation.

### ISSUE THREAD

**Issue by mizzao** [abrookins/WrapToColumn#4]
Thanks for this plugin! It's quite needed. I just noticed one minor potential improvement:

Suppose I have the following

```
  # This is a line. This is a line. This is a line. This is a line. This is a line.
  # This is a second line.
```

The indentation depends on whether I select the first whole line or not. Suppose I use the default caret position from the editor and select from the end of the first indent and the whole second line, then the following occurs:

```
  # This is a line. This is a line. This is a line. This is a line. This is a
# line. This is a second line.
```

If i take extra care to select the whole first line, I get the correct result:

```
  # This is a line. This is a line. This is a line. This is a line. This is a
  # line. This is a second line.
```

Not sure if there's a case where we'd want the first behavior, but maybe the right thing to do is just to indent everything to the level of the first line. (Check emacs/vim source?)

**Comment by abrookins** [comment]
Should be fixed in 1.7.0, now published to the Plugins Marketplace.
