### ISSUE TITLE
Wrap paragraph to column breaks when adjacent to a JS spread

### ISSUE THREAD

**Issue by ericmatthys** [abrookins/WrapToColumn#57]
Here are a couple videos demonstrating the issue. A spread either immediately on the preceding line or following line will break things.

https://github.com/abrookins/WrapToColumn/assets/1154586/51ab6a27-3aae-44ad-94d4-615449e407f0

https://github.com/abrookins/WrapToColumn/assets/1154586/b4231bb0-2ba3-4512-80e7-4d79d872a2bb

**Comment by abrookins** [comment]
@ericmatthys This should be fixed in 1.9.1. That release is still in the review queue in the JetBrains marketplace, after which it'll go out as an automatic update. However, you can manually install 1.9.1 to try it here: https://github.com/abrookins/WrapToColumn/releases/tag/1.9.1

**Comment by abrookins** [comment]
u
