### ISSUE TITLE
No keyboard shortcut for Windows users

### ISSUE THREAD

**Issue by abrookins** [abrookins/WrapToColumn#6]
The plugin ships with a shortcut that only works on Linux and OS X. That is not very kind to our Windows friends.

**Comment by islemaster** [comment]
FYI, I'm on Ubuntu 15.04 and after installing your plugin today it already had a keyboard shortcut: `Meta`+`Ctrl`+`Shift`+`W`.

Does exactly what I need, by the way.  I was amazed that this isn't built-in somewhere.  Thanks for building this!

**Comment by abrookins** [comment]
Awesome, dude! Thank you for providing the Linux perspective. I now feel that the default shortcut I chose was hateful in many ways, but I'm not sure how to fix it -- I assume everyone just remaps it anyway.
