### ISSUE TITLE
Cannot override "Plaintext filetypes" option

### ISSUE THREAD

**Issue by feltech** [abrookins/WrapToColumn#62]
Using CLion 2024.1.4. 

When I update the text box in File->Settings->Tools->Wrap to Column->Plaintext filetypes, then click OK, the setting is not applied. Re-opening the settings reveals the same default list and my edits have disappeared.

I wanted to get rid of `.txt` from that list, since I want to support wrapping `#` comments in `CMakeLists.txt` files.

**Comment by abrookins** [comment]
I'll check this out! Thanks for reporting.

**Comment by abrookins** [comment]
Fixed in #60, published in 1.9.0.

**Comment by abrookins** [comment]
Reopen if that doesn't solve it, and thanks for reporting!
