### ISSUE TITLE
Does not use code-style-specific column width

### ISSUE THREAD

**Issue by garaden** [abrookins/WrapToColumn#9]
For example, if my global setting is 120 characters but HTML files are set to 100, WrapToColumn wraps to 120 characters.

**Comment by abrookins** [comment]
Hey, thanks for letting me know about this! It sounds like I need to update the plugin to support file-specific widths.

**Comment by garaden** [comment]
Yup, no problem! I couldn't find the appropriate place in IDEA's API (didn't look very hard), but yeah, that should do it.

**Comment by abrookins** [comment]
Release 1.0 should fix this. Thanks again!

**Comment by garaden** [comment]
Works great for me, thanks!

**Comment by abrookins** [comment]
Yay!! :rainbow:
